spring:
  application:
    name: WalletMerchants
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wallet?autoReconnect=true
    username: root
    password:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: wallet
      listener:
        concurrency: 4

server:
  port: 9527

logging:
  level: debug
  file:
    name: wallet-merchants.log
